spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/certificatessystem
    username : root
    password : root
    datasource:
      type: com.zaxxer.hikari.HikariDataSource